
NOTIFICATION_TYPE_CRON_TRIGGER = 'cron_trigger_notification'

NOTIFICATION_TYPE_PP_COMPLETE_DOWNLOAD_COMPLETE = 'pp_complete_download_complete_notification'
NOTIFICATION_TYPE_PP_MONTHLY_UPDATE_DOWNLOAD_COMPLETE = 'pp_monthly_update_download_complete_notification'

NOTIFICATION_TYPE_PP_COMPLETE_DATA_DECISION_COMPLETE = 'pp_complete_data_decision_complete_notification'
NOTIFICATION_TYPE_PP_MONTHLY_UPDATE_DATA_DECISION_COMPLETE = 'pp_monthly_update_data_decision_complete_notification'

NOTIFICATION_TYPE_PP_COMPLETE_GC_COMPLETE = 'pp_complete_gc_complete_notification'
NOTIFICATION_TYPE_PP_MONTHLY_UPDATE_GC_COMPLETE = 'pp_monthly_update_gc_complete_notification'

NOTIFICATION_TYPE_PP_COMPLETE_ARCHIVE_COMPLETE = 'pp_complete_archive_complete_notification'
NOTIFICATION_TYPE_PP_MONTHLY_UPDATE_ARCHIVE_COMPLETE = 'pp_monthly_update_archive_complete_notification'

NOTIFICATION_TYPE_PP_COMPLETE_DB_UPLOAD_COMPLETE = 'pp_complete_db_upload_complete_notification'
NOTIFICATION_TYPE_PP_MONTHLY_UPDATE_DB_UPDATE_COMPLETE = 'pp_complete_db_update_complete_notification'
