
PROCESS_NAME_CRON_TRIGGER = 'land_registry_cron_trigger'

PROCESS_NAME_PP_COMPLETE_DOWNLOADER = 'land_registry_pp_complete_downloader'
PROCESS_NAME_PP_COMPLETE_SHASUM_CALCULATOR = 'land_registry_pp_complete_shasum_calculator'
PROCESS_NAME_PP_COMPLETE_DATA_DECISION = 'land_registry_pp_complete_data_decision'
PROCESS_NAME_PP_COMPLETE_GARBAGE_COLLECTOR = 'land_registry_pp_complete_garbage_collector'
PROCESS_NAME_PP_COMPLETE_ARCHIVER = 'land_registry_pp_complete_archiver'

PROCESS_NAME_PP_MONTHLY_UPDATE_DOWNLOADER = 'land_registry_pp_monthly_update_downloader'
PROCESS_NAME_PP_MONTHLY_UPDATE_SHA256_CALCULATOR = 'land_registry_pp_monthly_update_shasum_calculator'
PROCESS_NAME_PP_MONTHLY_UPDATE_DATA_DECISION = 'land_registry_pp_monthly_update_data_decision'
PROCESS_NAME_PP_MONTHLY_UPDATE_GARBAGE_COLLECTOR = 'land_registry_pp_monthly_update_garbage_collector'
PROCESS_NAME_PP_MONTHLY_UPDATE_ARCHIVER = 'land_registry_pp_monthly_update_archiver'

# PROCESS_NAME_LAND_REGISTRY_DATA_PP_MONTHLY_UPDATE_DATABASE_UPDATER = 'land_registry_monthly_update_database_updater'
