#!/bin/bash

# TODO: log directory?
# systemctl log redirection?

set -euo pipefail

if [[ "$(id -u)" != "0" ]]; then
    echo "This script must be run as root" >&2
    exit 1
fi

APPLICATION_GROUP_NAME="property-price-land-registry-download"

NAME_CRON_TRIGGER="land_registry_cron_trigger"
NAME_COMPLETE_DOWNLOADER="land_registry_complete_downloader"
NAME_MONTHLY_UPDATE_DOWNLOADER="land_registry_monthly_update_downloader"
NAME_MONTHLY_UPDATE_SHA_CALCULATOR="land_registry_monthly_update_sha256_calculator"
NAME_MONTHLY_UPDATE_DATA_DECISION="land_registry_monthly_update_data_decision"
NAME_MONTHLY_UPDATE_DATABASE_UPDATER="land_registry_monthly_update_database_updater"
NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR="land_registry_monthly_update_garbage_collector"

PROCESS_NAMES=(
    "$NAME_CRON_TRIGGER"
    "$NAME_COMPLETE_DOWNLOADER"
    "$NAME_MONTHLY_UPDATE_DOWNLOADER"
    "$NAME_MONTHLY_UPDATE_SHA_CALCULATOR"
    "$NAME_MONTHLY_UPDATE_DATA_DECISION"
    "$NAME_MONTHLY_UPDATE_DATABASE_UPDATER"
    "$NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR"
)

PYTHON_NAMES=("${PROCESS_NAMES[@]/%/.py}")

SERVICE_FILE_NAMES=("${PROCESS_NAMES[@]/%/.service}")

# PYTHON_NAME_CRON_TRIGGER="$NAME_CRON_TRIGGER.py"
# PYTHON_NAME_COMPLETE_DOWNLOADER="$NAME_COMPLETE_DOWNLOADER.py"
# PYTHON_NAME_MONTHLY_UPDATE_DOWNLOADER="$NAME_MONTHLY_UPDATE_DOWNLOADER.py"
# PYTHON_NAME_MONTHLY_UPDATE_SHA_CALCULATOR="$NAME_MONTHLY_UPDATE_SHA_CALCULATOR.py"
# PYTHON_NAME_MONTHLY_UPDATE_DATA_DECISION="$NAME_MONTHLY_UPDATE_DATA_DECISION.py"
# PYTHON_NAME_MONTHLY_UPDATE_DATABASE_UPDATER="$NAME_MONTHLY_UPDATE_DATABASE_UPDATER.py"
# PYTHON_NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR="$NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR.py"

# SERVICE_FILE_NAME_CRON_TRIGGER="$NAME_CRON_TRIGGER.service"
# SERVICE_FILE_NAME_COMPLETE_DOWNLOADER="$NAME_COMPLETE_DOWNLOADER.service"
# SERVICE_FILE_NAME_MONTHLY_UPDATE_DOWNLOADER="$NAME_MONTHLY_UPDATE_DOWNLOADER.service"
# SERVICE_FILE_NAME_MONTHLY_UPDATE_SHA_CALCULATOR="$NAME_MONTHLY_UPDATE_SHA_CALCULATOR.service"
# SERVICE_FILE_NAME_MONTHLY_UPDATE_DATA_DECISION="$NAME_MONTHLY_UPDATE_DATA_DECISION.service"
# SERVICE_FILE_NAME_MONTHLY_UPDATE_DATABASE_UPDATER="$NAME_MONTHLY_UPDATE_DATABASE_UPDATER.service"
# SERVICE_FILE_NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR="$NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR.service"

SERVICE_USER=propertyprice
SERVICE_GROUP=propertyprice

BINARY_INSTALL_PATH_ROOT="/usr/local/bin/$APPLICATION_GROUP_NAME"
SYSTEMD_INSTALL_PATH_ROOT="/etc/systemd/system"
LOG_FILE_INSTALL_PATH_ROOT="/var/log/$APPLICATION_GROUP_NAME"

BINARY_LOCAL_PATH_ROOT=".."
SERVICE_FILE_LOCAL_PATH_ROOT="../systemd-unit-service-files"
SERVICE_TARGET_FILE_NAME="land_registry_data.target"

# Create service user and group
echo "create user $SERVICE_USER and group $SERVICE_GROUP"
if ! id "$SERVICE_USER" &>/dev/null; then
    groupadd $SERVICE_GROUP
    useradd -r -s /bin/false -g $SERVICE_GROUP $SERVICE_USER
fi

# Create install directory
echo "create install directory $BINARY_INSTALL_PATH_ROOT"
mkdir -p "$BINARY_INSTALL_PATH_ROOT"

# Copy library dependencies
echo "copy library dependencies"
cp "$BINARY_LOCAL_PATH_ROOT/requirements.txt" "$BINARY_INSTALL_PATH_ROOT/"
cp -r "$BINARY_LOCAL_PATH_ROOT/lib_land_registry_download" "$BINARY_INSTALL_PATH_ROOT/"
pushd "$BINARY_INSTALL_PATH_ROOT"
python3 -m venv .venv
source .venv/bin/activate
pip3 install -r requirements.txt
popd

# Copy python executables
# cp "$BINARY_LOCAL_PATH_ROOT/$PYTHON_NAME_CRON_TRIGGER" "$BINARY_INSTALL_PATH_ROOT/"
# cp "$BINARY_LOCAL_PATH_ROOT/$PYTHON_NAME_COMPLETE_DOWNLOADER" "$BINARY_INSTALL_PATH_ROOT/"
# cp "$BINARY_LOCAL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_DOWNLOADER" "$BINARY_INSTALL_PATH_ROOT/"
# cp "$BINARY_LOCAL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_SHA_CALCULATOR" "$BINARY_INSTALL_PATH_ROOT/"
# cp "$BINARY_LOCAL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_DATA_DECISION" "$BINARY_INSTALL_PATH_ROOT/"
# cp "$BINARY_LOCAL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_DATABASE_UPDATER" "$BINARY_INSTALL_PATH_ROOT/"
# cp "$BINARY_LOCAL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR" "$BINARY_INSTALL_PATH_ROOT/"
for i in "${!PYTHON_NAMES[@]}"; do
    PYTHON_NAME="${PYTHON_NAMES[$i]}"
    echo "installing $PYTHON_NAME to $BINARY_INSTALL_PATH_ROOT"
    cp "$BINARY_LOCAL_PATH_ROOT/$PYTHON_NAME" "$BINARY_INSTALL_PATH_ROOT/"
done

# Ensure python executables are executable
# chmod +x "$BINARY_INSTALL_PATH_ROOT/$PYTHON_NAME_CRON_TRIGGER"
# chmod +x "$BINARY_INSTALL_PATH_ROOT/$PYTHON_NAME_COMPLETE_DOWNLOADER"
# chmod +x "$BINARY_INSTALL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_DOWNLOADER"
# chmod +x "$BINARY_INSTALL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_SHA_CALCULATOR"
# chmod +x "$BINARY_INSTALL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_DATA_DECISION"
# chmod +x "$BINARY_INSTALL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_DATABASE_UPDATER"
# chmod +x "$BINARY_INSTALL_PATH_ROOT/$PYTHON_NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR"
for i in "${!PYTHON_NAMES[@]}"; do
    PYTHON_NAME="${PYTHON_NAMES[$i]}"
    echo "chmod +x $PYTHON_NAME"
    chmod +x "$BINARY_INSTALL_PATH_ROOT/$PYTHON_NAME"
done

# Copy systemd service files
# cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_FILE_NAME_CRON_TRIGGER" "$SYSTEMD_INSTALL_PATH_ROOT/"
# cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_FILE_NAME_COMPLETE_DOWNLOADER" "$SYSTEMD_INSTALL_PATH_ROOT/"
# cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_FILE_NAME_MONTHLY_UPDATE_DOWNLOADER" "$SYSTEMD_INSTALL_PATH_ROOT/"
# cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_FILE_NAME_MONTHLY_UPDATE_SHA_CALCULATOR" "$SYSTEMD_INSTALL_PATH_ROOT/"
# cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_FILE_NAME_MONTHLY_UPDATE_DATA_DECISION" "$SYSTEMD_INSTALL_PATH_ROOT/"
# cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_FILE_NAME_MONTHLY_UPDATE_DATABASE_UPDATER" "$SYSTEMD_INSTALL_PATH_ROOT/"
# cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_FILE_NAME_MONTHLY_UPDATE_GARBAGE_COLLECTOR" "$SYSTEMD_INSTALL_PATH_ROOT/"
echo "installing $SERVICE_TARGET_FILE_NAME to $SYSTEMD_INSTALL_PATH_ROOT"
cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_TARGET_FILE_NAME" "$SYSTEMD_INSTALL_PATH_ROOT/"

for i in "${!SERVICE_FILE_NAMES[@]}"; do
    SERVICE_FILE_NAME="${SERVICE_FILE_NAMES[$i]}"
    echo "installing $SERVICE_FILE_NAME to $SYSTEMD_INSTALL_PATH_ROOT"
    cp "$SERVICE_FILE_LOCAL_PATH_ROOT/$SERVICE_FILE_NAME" "$SYSTEMD_INSTALL_PATH_ROOT/"
done

# Create log directory
echo "create log directory $LOG_FILE_INSTALL_PATH_ROOT"
mkdir -p "$LOG_FILE_INSTALL_PATH_ROOT"
chown propertyprice:propertyprice "$LOG_FILE_INSTALL_PATH_ROOT"
chmod 755 "$LOG_FILE_INSTALL_PATH_ROOT"

# Reload systemctl to pick up new service files
echo "reload systemctl"
systemctl daemon-reload

# TODO: run python scripts with a shell script?

echo "$APPLICATION_GROUP_NAME installation complete"
