
TOPIC_NAME_CRON_TRIGGER_NOTIFICATION = 'land_registry_data.cron_trigger.notification'

TOPIC_NAME_PP_COMPLETE_DOWNLOAD_NOTIFICATION = 'land_registry_data.pp_complete_download.notification'
TOPIC_NAME_PP_MONTHLY_UPDATE_DOWNLOAD_NOTIFICATION = 'land_registry_data.pp_monthly_update_download.notification'

TOPIC_NAME_PP_COMPLETE_DATA_DECISION_NOTIFICATION = 'land_registry_data.pp_complete_data_decision.notification'
TOPIC_NAME_PP_MONTHLY_UPDATE_DATA_DECISION_NOTIFICATION = 'land_registry_data.pp_monthly_update_data_decision.notification'

TOPIC_NAME_PP_COMPLETE_GC_NOTIFICATION = 'land_registry_data.pp_complete_gc.notification'
TOPIC_NAME_PP_MONTHLY_UPDATE_GC_NOTIFICATION = 'land_registry_data.pp_monthly_update_gc.notification'

TOPIC_NAME_PP_COMPLETE_ARCHIVE_NOTIFICATION = 'land_registry_data.pp_complete_archive.notification'
TOPIC_NAME_PP_MONTHLY_UPDATE_ARCHIVE_NOTIFICATION = 'land_registry_data.pp_monthly_update_archive.notification'

TOPIC_NAME_PP_COMPLETE_DB_UPLOAD_NOTIFICATION = 'land_registry_data.pp_complete_db_upload.notification'
TOPIC_NAME_PP_MONTHLY_UPDATE_DB_UPDATE_NOTIFICATION = 'land_registry_data.pp_monthly_update_db_update.notification'
