
topic_name_land_registry_download_controller_notification = 'daily_download.controller.notification'
topic_name_land_registry_download_downloader_notification = 'daily_download.downloader.notification'
topic_name_land_registry_download_monthly_update_downloader_notification = 'daily_download.monthly_update_downloader.notification'
topic_name_land_registry_download_monthly_update_sha256_calculator_notification = 'daily_download.monthly_update_sha256_calculator.notification'
topic_name_land_registry_download_monthly_update_data_decision_notification = 'daily_download.monthly_update_data_decision.notification'
topic_name_land_registry_download_monthly_update_database_updater_notification = 'daily_download.monthly_update_database_updater.notification'
topic_name_land_registry_download_monthly_update_garbage_collector_notification = 'daily_download.monthly_update_garbage_collector.notification'

# This should actually be called something like database verifier
# TODO: write the verification process
topic_name_land_registry_download_monthly_update_database_uploader_notification = 'daily_download.database_uploader.notification'
