systemctl status land_registry_cron_trigger.service
systemctl status land_registry_complete_downloader.service
systemctl status land_registry_monthly_update_downloader.service
systemctl status land_registry_monthly_update_sha256_calculator.service
systemctl status land_registry_monthly_update_data_decision.service
systemctl status land_registry_monthly_update_database_updater.service
systemctl status land_registry_monthly_update_garbage_collector.service