
DAILY_DOWNLOAD_TRIGGER = 'daily_download_trigger'
DAILY_DOWNLOAD_COMPLETE = 'daily_download_complete'
DAILY_DOWNLOAD_MONTHLY_UPDATE_COMPLETE = 'daily_download_monthly_update_complete'
DAILY_DOWNLOAD_MONTHLY_UPDATE_SHA256SUM_COMPLETE = 'daily_download_monthly_update_sha256sum_complete'
DAILY_DOWNLOAD_MONTHLY_UPDATE_DATA_DECISION_COMPLETE = 'daily_download_monthly_update_data_decision_complete'
DAILY_DOWNLOAD_MONTHLY_UPDATE_DATABASE_UPDATE_COMPLETE = 'daily_download_monthly_update_database_update_complete'
DAILY_DOWNLOAD_MONTHLY_UPDATE_GARBAGE_COLLECTION_COMPLETE = 'daily_download_monthly_update_garbage_collection_complete'
