
PROCESS_NAME_LAND_REGISTRY_CRON_TRIGGER = 'land_registry_cron_trigger'
PROCESS_NAME_LAND_REGISTRY_COMPLETE_DOWNLOADER = 'land_registry_complete_downloader'
PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_DOWNLOADER = 'land_registry_monthly_update_downloader'
PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_SHA256_CALCULATOR = 'land_registry_monthly_update_sha256_calculator'
PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_DATA_DECISION = 'land_registry_monthly_update_data_decision'
PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_DATABASE_UPDATER = 'land_registry_monthly_update_database_updater'
PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_GARBAGE_COLLECTOR = 'land_registry_monthly_update_garbage_collector'

OLD_PROCESS_NAME_LAND_REGISTRY_CRON_TRIGGER = 'daily_download_controller'
OLD_PROCESS_NAME_LAND_REGISTRY_COMPLETE_DOWNLOADER = 'daily_download_downloader'
OLD_PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_DOWNLOADER = 'daily_download_monthly_update_downloader'
OLD_PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_SHA256_CALCULATOR = 'daily_download_monthly_update_sha256_calculator'
OLD_PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_DATA_DECISION = 'daily_download_monthly_update_data_decision'
OLD_PROCESS_NAME_LAND_REGISTRY_MONTHLY_UPDATE_DATABASE_UPDATER = 'daily_download_monthly_update_database_updater'




